apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: {{template "chat.fullname" .}}-mongo
  name: {{template "chat.fullname" .}}-mongo
spec:
  replicas: {{.Values.replicas_mongo}}
  selector:
    matchLabels:
      run: {{template "chat.fullname" .}}-mongo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: {{template "chat.fullname" .}}-mongo
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{template "chat.fullname" .}}-mongo
  name: {{template "chat.fullname" .}}-mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: {{template "chat.fullname" .}}-mongo
